local ds1 = {}

ds1.templates = {
    "* ahead",
    "Be wary of *",
    "Try *",
    "Need *",
    "Imminent *...",
    "Weakness: *",
    "*",
    "*?",
    "Good Luck",
    "I did it!",
    "Here!",
    "I can't take this...",
    "Praise the Sun!",
}

local words = {}
ds1.words = words

words.characters = {
    "Enemy",
    "Tough enemy",
    "Hollow",
    "Soldier",
    "Knight",
    "Sniper",
    "Caster",
    "Giant",
    "Skeleton",
    "Ghost",
    "Bug",
    "Poison bug",
    "Lizard",
    "Drake",
    "Flier",
    "Golem",
    "Statue",
    "Monster",
    "Strange creature",
    "Demon",
    "Darkwraith",
    "Dragon",
    "Boss",
}

words.objects = {
    "Bonfire",
    "Fog wall",
    "Humanity",
    "Lever",
    "Switch",
    "Key",
    "Treasure",
    "Chest",
    "Weapon",
    "Shield",
    "Projectile",
    "Armour",
    "Item",
    "Ring",
    "Sorcery scroll",
    "Pyromancy scroll",
    "Miracle scroll",
    "Ember",
    "Trap",
    "Covenant",
    "Amazing key",
    "Amazing treasure",
    "Amazing chest",
}

words.techniques = {
    "Close-ranged battle",
    "Ranged battle",
    "Eliminating one at a time",
    "Luring it out",
    "Beating to a pulp",
    "Lying in ambush",
    "Stealth",
    "Mimicry",
    "Pincer attack",
    "Hitting them in one swoop",
    "Fleeing",
    "Charging",
    "Stabbing in the back",
    "Sweeping attack",
    "Shield breaking",
    "Head shots",
    "Sorcery",
    "Pyromancy",
    "Miracles",
    "Jumping off",
    "Sliding down",
    "Dashing through",
}

words.actions = {
    "Rolling",
    "Backstepping",
    "Jumping",
    "Attacking",
    "Holding with both hands",
    "Kicking",
    "A plunging attack",
    "Blocking",
    "Parrying",
    "Locking-on",
}

words.geography = {
    "Path",
    "Hidden path",
    "Shortcut",
    "Detour",
    "Illusionary wall",
    "Shortcut",
    "Dead end",
    "Swamp",
    "Lava",
    "Forest",
    "Cave",
    "Labyrinth",
    "Safe zone",
    "Danger zone",
    "Sniper spot",
    "Bright spot",
    "Dark spot",
    "Open area",
    "Tight spot",
    "Hidden place",
    "Exchange",
    "Gorgeous view",
    "Fall",
}

words.orientation = {
    "Front",
    "Back",
    "Left",
    "Right",
    "Up",
    "Down",
}

words.bodyParts = {
    "Head",
    "Neck",
    "Stomach",
    "Back",
    "Arm",
    "Leg",
    "Heel",
    "Rear",
    "Tail",
    "Wings",
    "Anywhere",
}

words.attributes = {
    "Strike",
    "Thrust",
    "Slash",
    "Magic",
    "Fire",
    "Lightning",
    "Critical hits",
    "Bleeding",
    "Poison",
    "Strong poison",
    "Curses",
    "Divine",
    "Occult",
    "Crystal",
}

return ds1