local sekiro = {}

sekiro.templates = {
    "*",
    "*...",
    "might be *",
    "hm. so it's a *",
    "which means... *",
    "* you say...",
    "*...!",
    "ought to be *...",
    "surely not *...",
    "what is a *...?",
    "*...?",
    "it's not a *",
    "*... I'll think about it",
    "*? I see...",
    "in case of *...",
    "perform *",
    "should try *",
    "confront *",
    "while *",
    "avoid *",
    "no need for *",
    "the pinnacle of *",
    "offer to *",
    "for the sake of *...",
    "* is precious...",
    "surely, not *",
    "code of *"
}

sekiro.conjunctions = {
    "and",
    "because",
    "all the more",
    "therefore",
    "but",
    "is",
    "in short",
    "that is to say",
    "or",
    "also",
    "however",
    "if",
    "then",
    "by the way",
    "as it were",
    ","
}

local words = {}
sekiro.words = words

words.people = {
    "divine child",
    "divine heir",
    "Kuro",
    "Lord Kuro",
    "sculptor",
    "physician",
    "memorial mob",
    "peddler",
    "Wolf",
    "Sekiro",
    "I",
    "me",
    "oneself",
    "you",
    "equal",
    "superior",
    "comrade",
    "pious one",
    "villain",
    "forlorn",
    "misfit",
    "graceful one",
    "swift one",
    "straggler",
    "brute",
    "mule",
    "horror",
    "moneybags",
    "vagabond",
    "deserter",
    "cheat",
    "fiend",
    "youth",
    "man",
    "woman",
    "elder",
    "geezer",
    "hag",
    "master",
    "friend",
    "ally",
    "lord",
    "parent",
    "foster father",
    "child"
}

words.enemiesBeastsAndMonsters = {
    "enemy",
    "foe",
    "worthy opponent",
    "extraordinary foe",
    "shinobi",
    "bandit",
    "villager",
    "Ashina clan",
    "sniper",
    "fencer",
    "warrior",
    "seeker",
    "beast",
    "hound",
    "monkey",
    "serpent",
    "insect",
    "parasite",
    "gamefowl",
    "monster",
    "spirit",
    "apparition",
    "infested",
    "undying",
    "demon",
    "shura"
}

words.objects = {
    "sculptor's idol",
    "offering box",
    "treasure",
    "chest",
    "mechanism",
    "tatami mat",
    "under the floor",
    "door",
    "key",
    "trap",
    "sen",
    "katana",
    "shinobi prosthetic",
    "item",
    "valuable item",
    "material",
    "gourd",
    "sugar",
    "balloon",
    "spirit emblem",
    "document",
    "blood",
    "rice",
    "sake",
    "prayer bead",
    "prayer necklace",
    "memory",
    "remnant"
}

words.tactics = {
    "swordplay",
    "projectile",
    "mid-air battle",
    "stealth",
    "reconnaisance",
    "taking them one by one",
    "luring out",
    "ambushing",
    "pincer attack",
    "taking them all at once",
    "fleeing",
    "charging",
    "jumping off",
    "sprinting through",
    "flanking",
    "leaving to fate",
    "caution",
    "distracting",
    "controlling",
    "stripping away",
    "feigning death",
}

words.techniques = {
    "movement",
    "sprinting",
    "grappling hook",
    "jumping",
    "crouching",
    "jump kick",
    "attacking",
    "sweep attack",
    "grab attack",
    "thrust attack",
    "counter-slash attack",
    "shinobi deathblow",
    "backstab deathblow",
    "plunging deathblow",
    "guard",
    "deflecting",
    "consecutive deflects",
    "mikiri counter",
    "evasion",
    "ledge hang",
    "wall hug",
    "peeking",
    "swimming",
    "eavesdropping"
}

words.locations = {
    "castle keep",
    "outskirts",
    "village",
    "rooftop",
    "hallway",
    "stairs",
    "temple",
    "valley",
    "cliff",
    "abyss",
    "mountain path",
    "forest",
    "treetop",
    "swamp",
    "cave",
    "tall grass",
    "underwater",
    "water surface",
    "mid-air",
    "shortcut",
    "detour",
    "hidden path",
    "escape route",
    "dead end",
    "bright place",
    "dark place",
    "open place",
    "cramped place",
    "safe area",
    "dangerous area",
    "ladder",
    "stunning view",
    "oversight",
    "misfortune",
    "carelessness",
    "encounter",
    "enemy group",
    "lone enemy",
    "enemy patrol",
    "training",
}

words.orientations = {
    "front",
    "back",
    "left",
    "right",
    "up",
    "down",
    "below",
    "above",
    "behind",
    "ahead"
}

words.attributes = {
    "poison",
    "burn",
    "terror",
    "shock",
    "enfeeblement",
    "fornidden",
    "sinister burden",
    "slash attacks",
    "blunt attacks",
    "thrust attacks",
    "ranged attacks",
    "flame",
    "apparition",
    "posture"
}

words.concepts = {
    "fighting chance",
    "escape",
    "perilous pass",
    "certain death",
    "secret",
    "gibberish",
    "bliss",
    "misery",
    "life",
    "death",
    "wrath",
    "pain",
    "sadness",
    "loyalty",
    "betrayal",
    "cowardice",
    "hope",
    "fear",
    "victory",
    "defeat",
    "sacrifice",
    "risk one's life",
    "relief",
    "vigor",
    "resignation",
    "critical moment",
    "regret",
    "futility",
    "friendship",
    "love",
    "abandon",
    "composure",
    "persistence",
    "solace",
    "quiet",
    "depth",
    "stagnation",
    "strength",
    "speed",
    "toughness",
    "skill",
    "hatred",
    "revenge",
    "repayment",
    "auspicious",
    "forboding",
    "panic",
    "hesitation",
    "comfort",
    "blink",
    "short",
    "long",
    "beautiful",
    "hideous"
}

words.musings = {
    "well done",
    "I've done it",
    "regretful...",
    "here...",
    "not here...",
    "no turning back...",
    "enough",
    "look carefully",
    "listen carefully",
    "think carefully",
    "this place again",
    "this is it",
    "is this a trick...?",
    "go",
    "go back",
    "give up",
    "stay strong",
    "impossible...",
    "so high up...",
    "so deep...",
    "keep calm...",
    "an illusion...",
    "nostalgic...",
    "prepare yourself...",
    "you'll know it when you see it",
    "as you command",
    "face me",
    "I don't mind",
    "yes",
    "no",
    "what...?",
    "alright",
    "I cannot",
    "I cannot say",
    "forgive me",
    "I don't think",
    "you have my gratitude",
    "farewell",
    "do what must be done",
    "I will lose",
    "........"
}

return sekiro